version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: icchecker_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password

  backend:
    container_name: icchecker_backend
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://user:password@mongo:27017

volumes:
  mongo_data: